In [379]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [380]:
import sklearn
from sklearn import datasets
from sklearn import preprocessing
from sklearn import metrics
from sklearn import model_selection

In [381]:
file_path = "Data/firestore_ai_training_data_20250324_173442.csv"
game_data = pd.read_csv(file_path) #data as .csv file?

In [382]:
game_data

currentDifficulty  currentPlayerLives                    id  levelsBeat  \
0                    2                   0  0EbSXFZTryuq8oIfT5XD           2   
1                    2                   3  0MHiDsJMOXccolv2iGBX           2   
2                    1                   3  0fNyt4XAYVfxmrqhzHiS           2   
3                    9                   0  166Ds8AdrIlJM4pJwq2l           2   
4                    1                   2  1FQeoJPdbjvdXsvMIHHX           3   
..                 ...                 ...                   ...         ...   
453                  8                   2  zjKGbmNvnMzEw0dGT1TZ           7   
454                  1                   3  zkDzIKcMEvhhYJkCtJy4           1   
455                  1                   0  zsZZHTI3xXZhscaJ39cC           1   
456                  4                   0  ztMqf7s3RfKt9f9j7zPK           2   
457                  3                   0  zvdJeJd1BRgKZ7aP9LfA           2   

     newDifficulty  playerLifeTimer  totalEnemiesKilled  totalPoints  
0                2        29.496090                   4          500  
1                2        20.071680                   3          500  
2                1        21.088810                   3          300  
3               10        12.886800                   0            0  
4                1        29.910000                   4          400  
..             ...              ...                 ...          ...  
453              9        49.470540                   5        46400  
454              2         8.352791                   1          100  
455              1        43.373280                   1          100  
456              5        45.579180                   1          800  
457              4         9.787905                   4          900  

[458 rows x 8 columns]

## Data Preprocesing

In [383]:
#possible data cleaning would go here

In [384]:
#normalizing data

In [385]:
game_data.columns

Index(['currentDifficulty', 'currentPlayerLives', 'id', 'levelsBeat',
       'newDifficulty', 'playerLifeTimer', 'totalEnemiesKilled',
       'totalPoints'],
      dtype='object')

In [386]:
game_data['newDifficulty'] = game_data['newDifficulty'] - game_data['currentDifficulty']

column_drop_name = 'newDifficulty'
columns_drop_name = ['newDifficulty', 'id']

x = game_data.drop(columns_drop_name, axis='columns')

y = pd.DataFrame()
y['Result'] = game_data[column_drop_name]

In [387]:
#split data into training and testing data
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, train_size = 0.8, test_size = 0.2)

In [388]:
X_train

currentDifficulty  currentPlayerLives  levelsBeat  playerLifeTimer  \
74                   4                   3           3        55.067900   
14                   1                   3           1        14.005690   
62                   1                   3           1        16.195820   
351                  1                   3           1        24.305250   
47                   2                   3           2        25.669130   
..                 ...                 ...         ...              ...   
176                  6                   0           2        34.053960   
55                   1                   3           1        12.603690   
302                  7                   0           6         8.070197   
148                  1                   0           5        99.860950   
298                  2                   0           2        25.335900   

     totalEnemiesKilled  totalPoints  
74                    4         3200  
14                    1          100  
62                    1          100  
351                   1          100  
47                    3          500  
..                  ...          ...  
176                   1         3200  
55                    1          100  
302                  17        17300  
148                  13         1275  
298                   4          500  

[366 rows x 6 columns]

In [389]:
y_train

Result
74        1
14        1
62        1
351       1
47        1
..      ...
176       0
55        1
302       0
148       0
298       0

[366 rows x 1 columns]

In [390]:
X_test

currentDifficulty  currentPlayerLives  levelsBeat  playerLifeTimer  \
255                  1                   3           7        25.412490   
209                  7                   1           8        28.027410   
1                    2                   3           2        20.071680   
199                  8                   0           7        23.852400   
300                  4                   0           3        11.271450   
..                 ...                 ...         ...              ...   
449                  4                   3           4        12.019890   
431                  1                   3           1         8.694397   
10                   1                   0           1        29.389040   
390                  3                   2           3        18.347710   
118                  6                   0           2        38.627710   

     totalEnemiesKilled  totalPoints  
255                   5          450  
209                   8        40400  
1                     3          500  
199                  20        34900  
300                   9         3700  
..                  ...          ...  
449                  11         5300  
431                   1          100  
10                    1          100  
390                   4         1600  
118                   1         3200  

[92 rows x 6 columns]

In [391]:
y_test

Result
255       0
209       1
1         0
199       0
300      -1
..      ...
449       1
431       1
10        0
390       0
118      -1

[92 rows x 1 columns]

## AI Model Training

In [392]:
#need to decide AI model

In [393]:
#Linear regression (temporary need to to decided model from previous line)
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train['Result'])

DecisionTreeClassifier()

## Testing Model Accuracy + Other Metrics

In [394]:
X_test

currentDifficulty  currentPlayerLives  levelsBeat  playerLifeTimer  \
255                  1                   3           7        25.412490   
209                  7                   1           8        28.027410   
1                    2                   3           2        20.071680   
199                  8                   0           7        23.852400   
300                  4                   0           3        11.271450   
..                 ...                 ...         ...              ...   
449                  4                   3           4        12.019890   
431                  1                   3           1         8.694397   
10                   1                   0           1        29.389040   
390                  3                   2           3        18.347710   
118                  6                   0           2        38.627710   

     totalEnemiesKilled  totalPoints  
255                   5          450  
209                   8        40400  
1                     3          500  
199                  20        34900  
300                   9         3700  
..                  ...          ...  
449                  11         5300  
431                   1          100  
10                    1          100  
390                   4         1600  
118                   1         3200  

[92 rows x 6 columns]

In [395]:
y_predict = dt.predict(X_test)

In [396]:
y_predict

array([ 0,  1,  1,  1, -1,  0,  1,  1,  1,  0,  1,  1,  0,  1,  1,  1,  1,
        0,  1, -1,  1,  0,  1,  1,  0,  0,  1,  0,  1,  1,  1,  0, -1,  1,
        1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  0,
        1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  1,  1, -1,  0,  1,  0,  1,  1,  0,
        1,  0,  1,  1,  0,  1,  1], dtype=int64)

In [397]:
sklearn.metrics.accuracy_score(y_test, y_predict)

0.6956521739130435

In [398]:
sklearn.metrics.precision_recall_fscore_support(y_test, y_predict) #might need to add average = 'macro'

(array([0.6       , 0.66666667, 0.72222222]),
 array([0.33333333, 0.61111111, 0.82978723]),
 array([0.42857143, 0.63768116, 0.77227723]),
 array([ 9, 36, 47], dtype=int64))

In [399]:
## Saving Model Weights

In [400]:
from joblib import dump, load
dump(dt, 'filename.joblib')
dt = load('filename.joblib')